# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - name: AWS_ACCESS_KEY_ID
    value: $(AWS_ACCESS_KEY_ID)
  - name: AWS_SECRET_ACCESS_KEY
    value: $(AWS_SECRET_ACCESS_KEY)
  - name: AWS_DEFAULT_REGION
    value: $(AWS_DEFAULT_REGION)
  - name: EC2_INSTANCE_IP
    value: $(EC2_INSTANCE_IP)
  - name: TOMCAT_MANAGER_USER
    value: $(TOMCAT_MANAGER_USER)
  - name: TOMCAT_MANAGER_PASSWORD
    value: $(TOMCAT_MANAGER_PASSWORD)
jobs:
- job: DeployToTomcat
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: TomcatDeployment@1
    inputs:
      TomcatUrl: 'http://$(EC2_INSTANCE_IP):8080'
      Username: $(TOMCAT_MANAGER_USER)
      Password: $(TOMCAT_MANAGER_PASSWORD)
      Warfile: 'target/mvnwebapp.war'
      Context: '/azure-deploy'
      ServerVersion: '7OrAbove'
