trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Job'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'

  - task: TomcatDeployment@1
    inputs:
      TomcatUrl: 'http://65.1.136.13:8080'
      Username: 'pavan'
      Password: 'Pavan@123'
      Warfile: 'target/mvnwebapp.war'
      Context: '/azure-deploy'
      ServerVersion: '7OrAbove'
