trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '2.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: PowerShell@2
  displayName: 'Install AWS CLI'
  inputs:
    targetType: 'inline'
    script: |
      Invoke-WebRequest -Uri https://awscli.amazonaws.com/AWSCLIV2.msi -OutFile AWSCLIV2.msi
      Start-Process msiexec.exe -ArgumentList '/i', 'AWSCLIV2.msi', '/quiet' -Wait

- task: PowerShell@2
  displayName: 'Configure AWS CLI'
  inputs:
    targetType: 'inline'
    script: |
      aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
      aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
      aws configure set default.region ap-south-1

- task: DownloadPipelineArtifact@2
  inputs:
    artifact: 'MyWarArtifact'
    path: '$(Pipeline.Workspace)'
    patterns: '**/*.war'

- task: PowerShell@2
  displayName: 'Copy WAR file to Tomcat webapps directory'
  inputs:
    targetType: 'inline'
    script: |
      Copy-Item -Path "$(Pipeline.Workspace)\*.war" -Destination "C:\path\to\your\tomcat\webapps\"
      Restart-Service -Name 'Tomcat'  # Adjust the service name based on your Tomcat setup
