trigger:
  branches:
    exclude:
      - '*'

pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    version: '2.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: AWSCodeDeploy@1
  displayName: 'Install AWS Toolkit'
  inputs:
    installOrUpdateAWSToolkit: true

- task: AWSCodeDeploy@1
  displayName: 'Configure AWS CLI'
  inputs:
    awsRegion: 'us-east-1'
    awsAccessKeyId: $(AWS_ACCESS_KEY_ID)
    awsSecretAccessKey: $(AWS_SECRET_ACCESS_KEY)

- task: DownloadPipelineArtifact@2
  inputs:
    artifact: 'MyWarArtifact'
    path: '$(Pipeline.Workspace)'
    patterns: '**/*.war'

- task: PowerShell@2
  displayName: 'Copy WAR file to Tomcat webapps directory'
  inputs:
    targetType: 'inline'
    script: |
      Copy-Item -Path "$(Pipeline.Workspace)\*.war" -Destination "C:\path\to\your\tomcat\webapps\"
      Restart-Service -Name 'Tomcat'  # Adjust the service name based on your Tomcat setup
